platform :ios do
  desc "Deploy ios app on the appstore"

  lane :deploy do
    cordova(platform: 'ios',type:'development',release:'false')
  end
end

platform :android do
  desc "Deploy android app on play store"

  lane :deploy do
    cordova(
      platform: 'android',
      keystore_path: './gcox-key.jks',
      keystore_alias: 'key0',
      keystore_password: '123456'
    )
    #supply(apk: ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH'])
  end
end