platform :ios do
  desc "Deploy ios app on the appstore"
  lane :beta do
    cordova(platform: 'ios',type:'development',release:'false')

  end

    desc "Deploy ios app on the box"
    lane :deploy do
      cordova(platform: 'ios',type:'development',release:'false')
      resign(ipa:ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'],signing_identity:"iPhone Distribution: GCOX Technology Pte Ltd (XJWAJMQ92S)",provisioning_profile:"prod.mobileprovision")
      testflight(ipa: ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'],skip_waiting_for_build_processing:"true")
    end
end

platform :android do
  desc "Deploy android app on play store"

  lane :deploy do
    cordova(
      platform: 'android',
      keystore_path: './gcox-key.jks',
      keystore_alias: 'key0',
      keystore_password: '123456'
    )
    #supply(apk: ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH'])
  end
end